# Generated by Django 5.1.1 on 2024-10-20 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notascdm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas',
            new_name='Nota',
        ),
    ]
