# Generated by Django 5.1.1 on 2024-10-21 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notascdm_app', '0002_rename_notas_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='anio_calendario',
            field=models.IntegerField(verbose_name='Año Calendario'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='division',
            field=models.CharField(max_length=1, verbose_name='División'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='notascdm_app.alumno', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='notascdm_app.materia', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='descripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='notascdm_app.descripcion', verbose_name='Descripción'),
        ),
    ]
